# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from sdbx.api.paths.api_v1_prompts.get.operation import ApiForGet
from sdbx.api.paths.api_v1_prompts.post.operation import ApiForPost


class ApiV1Prompts(
    ApiForGet,
    ApiForPost,
):
    pass
