# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from sdbx.api.paths.interrupt.post.operation import ApiForPost


class Interrupt(
    ApiForPost,
):
    pass
