# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from sdbx.api.paths.prompt.get.operation import ApiForGet
from sdbx.api.paths.prompt.post.operation import ApiForPost


class Prompt(
    ApiForGet,
    ApiForPost,
):
    pass
