# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from sdbx.api.paths.queue.get.operation import ApiForGet
from sdbx.api.paths.queue.post.operation import ApiForPost


class Queue(
    ApiForGet,
    ApiForPost,
):
    pass
