# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from sdbx.api.paths.solidus.get.operation import ApiForGet


class Solidus(
    ApiForGet,
):
    pass
