blank_issues_enabled: false
contact_links:
  - name: Shadowbox - Matrix
    url: https://app.element.io/#/room/%23sdbx%3Amatrix.org
    about: Support and general discussion via Matrix, an open source Discordlike.
