# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from sdbx.api.paths.api_v1_images_digest.get.operation import ApiV1ImagesDigestGet
from sdbx.api.paths.api_v1_prompts.get.operation import ApiV1PromptsGet
from sdbx.api.paths.api_v1_prompts.post.operation import ApiV1PromptsPost
from sdbx.api.paths.prompt.get.operation import GetPrompt
from sdbx.api.paths.prompt.post.operation import PostPrompt
from sdbx.api.paths.extensions.get.operation import GetExtensions
from sdbx.api.paths.interrupt.post.operation import PostInterrupt
from sdbx.api.paths.history.get.operation import GetHistory
from sdbx.api.paths.history.post.operation import PostHistory
from sdbx.api.paths.queue.get.operation import GetQueue
from sdbx.api.paths.queue.post.operation import PostQueue
from sdbx.api.paths.upload_image.post.operation import UploadImage
from sdbx.api.paths.object_info.get.operation import GetObjectInfo
from sdbx.api.paths.view.get.operation import ViewImage
from sdbx.api.paths.embeddings.get.operation import GetEmbeddings
from sdbx.api.paths.solidus.get.operation import GetRoot


class DefaultApi(
    ApiV1ImagesDigestGet,
    ApiV1PromptsGet,
    ApiV1PromptsPost,
    GetPrompt,
    PostPrompt,
    GetExtensions,
    PostInterrupt,
    GetHistory,
    PostHistory,
    GetQueue,
    PostQueue,
    UploadImage,
    GetObjectInfo,
    ViewImage,
    GetEmbeddings,
    GetRoot,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
